version: '3.9'
services:
  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sitedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mysql:
