name: Deploy dev_move_nextjs

on:
  push:
    branches:
      - dev_move_nextjs

# デフォルトの作業ディレクトリ変更
# ルート直下の場合は不要
defaults:
  run:
    working-directory:  ./TDIC/clientapp


jobs:
  build-and-deploy:

    runs-on: ubuntu-22.04
    timeout-minutes: 300
    environment: production
    env:
      NODE_VERSION: 20.10.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        # 利用したいNode.jsバージョンを指定
        node-version: ${{ env.NODE_VERSION }}
        # npmのキャッシュを使用する設定
        cache: npm
        # ルート直下の場合は「./package-lock.json」に変更
        cache-dependency-path: ./TDIC/clientapp/package-lock.json

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-deps-${{ hashFiles('./TDIC/clientapp/**/package-lock.json') }}
        restore-keys: npm-deps-

    - name: Install dependencies
      run: npm ci

    - name: Deploy to netlify(main)
      run: netlify deploy --build --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_EXPERIMENT }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_EXPERIMENT }}
