name: Deploy dev_move_nextjs

on:
  push:
    branches:
      - dev_move_nextjs

jobs:
  build-and-deploy:

    runs-on: ubuntu-22.04
    timeout-minutes: 300
    environment: production
    env:
      NODE_VERSION: 18.16.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        # パスをプロジェクトが存在するサブディレクトリのnode_modulesに更新
        path: ./TDIC/clientapp/node_modules
        key: npm-deps-${{ hashFiles('./TDIC/clientapp/**/package-lock.json') }}
        restore-keys: npm-deps-

    - name: Install dependencies
      run: npm ci
      working-directory: ./TDIC/clientapp # コマンドを実行するディレクトリを指定

    - name: Deploy to netlify(main)
      run: netlify deploy --dir=./out --prod # ビルドされたファイルのディレクトリを指定
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      working-directory: ./TDIC/clientapp # コマンドを実行するディレクトリを指定